name: CI for LayerEdge Otomatis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.6'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y git curl build-essential libssl-dev pkg-config xz-utils cmake ninja-build

    - name: Install Rust
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain nightly
        source $HOME/.cargo/env
        rustup target add riscv32im-risc0-zkvm-elf --toolchain nightly

    - name: Install Risc0
      run: |
        curl -L https://risczero.com/install | bash
        rzup install cargo-risczero
        rzup install

    - name: Run install script
      run: |
        chmod +x install.sh
        sudo ./install.sh --ci-mode

    - name: Upload keys as artifact
      uses: actions/upload-artifact@v3
      with:
        name: node-keys
        path: light-node/keys.txt
